### ISSUE TITLE
Publicar vídeos apresentação YouTube

### ISSUE THREAD

**Issue by gabrielbdornas** [meadapt/apresentacoes#7]
Vídeos estão na máquina Gabriel.

## Atividades
- [x] Agendar os vídeos.
- [x] Incluir thumbanals.
- [x] Incluir descrição.
- [x] Melhorar Título.

**Comment by gabrielbdornas** [comment]
@raianecardoso, vídeos já estão agendados até 04/12/2024.Queria seu auxílio com a arte (itens não checados na [descrição](https://github.com/meadapt/apresentacoes/issues/7#issue-2630120498) do Issue).

**Comment by raianecardoso** [comment]
> [ ] Incluir thumbanals.

 Thumbnail criado no [Canva](https://www.canva.com/design/DAGV8Nm2WyQ/3xW6GlY__YRgPE4PgZiUlA/edit)

>Melhorar Título.

Adequação do nome da playlist e dos vídeos para: Doc as code: Crie Apresentações Incríveis com reveal.js 

> Incluir descrição.


Criado texto para descrição dos vídeos: 

Seja muito bem vindo à Me Adapt! 

Inspirados pela filosofia Documentation as Code (Docs as Code), preparamos essa playlist sobre como usar ferramentas de programação para gerar apresentações incríveis! Para isso, vamos usar o  reveal.js, que é um framework de código aberto que permite a qualquer pessoa com um navegador web criar apresentações, usando tecnologias como HTML5, CSS3 e JavaScript. 

Neste vídeo, vamos ver: 
- O que é a filosofia Documentation as Code (Docs as Code); 
- Os pré requisitos para colocar essa filosofia na prática, incluindo a instalação das ferramentas necessárias, comandos do terminal e uso do GitHub no nosso projeto

Confira a playlist completa : 

1.    Você está aqui!
2.    Doc as code: Crie Apresentações Incríveis com reveal.js - Part 2
3.    Doc as code: Crie Apresentações Incríveis com reveal.js - Part 3
4.    Doc as code: Crie Apresentações Incríveis com reveal.js - Part 4

_____________

Afinal, o que é a Me Adapt? 

A Me Adapt é, em sua essência, uma escola para você, que nos assiste, e também, para nós que produzimos o conteúdo que você encontra aqui. O nosso objetivo é aprendizado contínuo no universo da tecnologia e queremos compartilhar com você para que você seja capaz de se adaptar e construir uma nova realidade do seu jeito.

ACOMPANHE: https://meadapt.com 
Não deixe de conferir o nosso blog !

**Comment by gabrielbdornas** [comment]
@raianecardoso, não precisa nem escrever novamente que ficou incrível né!
